### ISSUE TITLE
Valueerror

### ISSUE THREAD

**Issue by Floreg2000** [brnorris03/GoogleCalendarAlarm#1]
After I run
>python gcal.py

It give me this

> Traceback (most recent call last):
>   _File "gcal.py", line 121, in <module>_
>     _main()_
>   _File "gcal.py", line 116, in main_
>     _checkCalendar(service)_
>   _File "gcal.py", line 98, in checkCalendar_
>     _sts  = datetime.strptime(ts.split('-')[0],'%H:%M:%S')_
>   _File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime_
>     _data_string[found.end():])_
> _ValueError: unconverted data remains: +01:00__

I really dont know what to do. So can you help me with solving this problem?

**Comment by roberthenzel** [comment]
sts = datetime.strptime(ts.split('-')[0],'%H:%M:%S')

splits on '-'. Author of this scripts is from West
You are obviously on East side of UTC zone because you are getting +01:00
Change this line to:
sts = datetime.strptime(ts.split('**+**')[0],'%H:%M:%S')
It should fix this bug.

**Comment by brnorris03** [comment]
I am most certainly not on the east side of UTC, in fact, I'm in PDT (UTC -7) .

**Comment by Floreg2000** [comment]
Thank you so much for the response.
I will try to the fix tomorrow. I am indeed on the East side of UTC so hopefully it wil work.

**Comment by brnorris03** [comment]
Thank you! It's a very handy app.
